import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "../globals.css";
import {Providers} from "@/app/providers";
import React from "react";


const poppins = Poppins({
    weight: ['400', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
      <Providers>
      <main>
        {children}
      </main>
      </Providers>
      </body>
    </html>
  );
}
