import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import {Providers} from "@/app/providers";
import React from "react";
import NavBarComponent from "@/components/navbar/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <Providers>
          <header>
              <NavBarComponent/>
          </header>
      <main>
        {children}
      </main>
      </Providers>
      </body>
    </html>
  );
}
